changelog:
  categories:
    - title: "New Features"
      labels:
        - enhancement
        - feature
    - title: "Bug Fixes"
      labels:
        - bug
        - fix
    - title: "Improvements"
      labels:
        - improvement
        - refactor
        - performance
    - title: "Other Changes"
      labels:
        - "*"
